FROM public.ecr.aws/lambda/go:1

# disables xray when running locally
ENV AWS_XRAY_SDK_DISABLED=TRUE

# project name arg to build
# build correct path to main.zip
ARG PROJECT_NAME

# copy over main.zip
ADD lambdas/link-generator/main.zip ${LAMBDA_TASK_ROOT}

RUN unzip -d ${LAMBDA_TASK_ROOT} ${LAMBDA_TASK_ROOT}/main.zip

# run main
CMD [ "main" ]